FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY ./backend/package*.json ./

RUN npm install

COPY ./backend/ ./

EXPOSE 8081
CMD ["node","app.js"]